version: "3.3"
services:
  web:
    image: pe-201642-agent.puppetdebug.vlan:5000/windows/win_php:latest
    ports:
      - target: 80
        published: 83
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints: [node.platform.OS == windows]
# Run: docker stack deploy -c docker-compose.yaml php
